### ISSUE TITLE
What's the API?

### ISSUE THREAD

**Issue by NiallMac** [simonsobs/so-lenspipe#13]
One thing I'm trying to work out with solenspipe is what the api should look like, by which I mean, how do we want the user to make the a pipeline do what they want it to do (for which we also need to define what the user would typically want to be doing!)? 

Presumably, we want some combination of a script (or a few, but not loads), and a config file (command line arguments are fine for overriding one or two things in the config file or overriding one or two defaults, but it's much safer to work with version-controlled config files in general). The script loads the config file and initializes an SOLensPipe instance (or more than one?) and then runs various of the methods (again probably specified in the config file) of SOLensPipe. So maybe good to discuss two or three use cases that we should design a reasonably general structure around.

**Comment by msyriac** [comment]
Here's what I broadly had in mind. The operations needed for maps->cosmology generically involve MPI-enabled stages that read stuff from disk, farm to processes and write products to disk at each stage. 

This means we could have an overarching pipeline driver, ideally not tied to this project (e.g. https://github.com/simonsobs/BBPipe or https://github.com/LSSTDESC/ceci ), but from which we can inherit classes specific to our needs. This something should generically create slurm-like scripts based on config files (yes, i agree on using command line arguments only to override defaults) and submit them in such a way that job dependencies are tied up (some stages start after others finish). The driver should enforce git-cleanliness and log commit hashes, command line overrides etc.

I have prototypes for some pieces of this. We can try to converge on specifics here!

**Comment by msyriac** [comment]
Just an update that after exploring a bit and chatting with David and Max, I'm thinking we should write the different stages of our pipeline (read products from, write products to disk) as classes that inherit from PipelineStage here: https://github.com/simonsobs/BBPipe . We can chat more about this on slack.

**Comment by msyriac** [comment]
Closing this since I think we have converged on using mbatch now:
https://github.com/simonsobs/mbatch
