### ISSUE TITLE
Missing 'README.rst' in master branch 

### ISSUE THREAD

**Issue by dwhan89** [simonsobs/so-lenspipe#14]
**User System Summary**
- OS: Linux 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- python version: python 3.7
- compilers: gfortran version 7.5.0, gcc version 7.5.0

------
**Issue Summary**

Attempted to compile the code with the command  `python setup.py build_ext -i ` on **master** branch
The compilation attempt failed with the following error messages. 

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    with open('README.rst') as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

```

**Comment by msyriac** [comment]
Should be fixed now

**Comment by dwhan89** [comment]
It is fixed now. Thanks!
